### ISSUE TITLE
Build fails with Visual Studio 2017 Version 15.8

### ISSUE THREAD

**Issue by Martin-Idel-SI** [osrf/osrf_testing_tools_cpp#15]
When building ROS from source using the latest Visual Studio 2017, this package fails to build.

The error is in the variant compatibility package and is also tracked upstream:
https://github.com/mpark/variant/issues/48

**Comment by brawner** [comment]
The upstream bug was resolved in late September. Is there anything else to resolve this issue?

**Comment by wjwwood** [comment]
I don't think so, I'll close and it can be reopened if needed.
