### ISSUE TITLE
Nightly ASan and TSan builds are failing to build osrf_testing_tools_cpp

### ISSUE THREAD

**Issue by prajakta-gokhale** [osrf/osrf_testing_tools_cpp#37]
Hi, there have been failures in the nightly ASan and TSan builds due to a linker error caused while building this package. These failures started around the time https://github.com/osrf/osrf_testing_tools_cpp/pull/36 (gtest version bump) was merged.

All build details are in https://github.com/ros-tooling/aws-oncall/issues/83.

**Comment by prajakta-gokhale** [comment]
@wjwwood could you please take a look?

**Comment by wjwwood** [comment]
I reverted the pull request that seems to have caused the issue. I'll leave this issue to you as to whether you want to track the problem or close it.

**Comment by prajakta-gokhale** [comment]
Thank you! Merging the linked PR should close this.
