### ISSUE TITLE
Build fails on MacOS Mojave after version 1.3.0 -> ld: library not found for -liberty

### ISSUE THREAD

**Issue by klintan** [osrf/osrf_testing_tools_cpp#49]
Tried building the latest master just now. 
I get `ld: library not found for -liberty` 

It is related to `backward-cpp`, trying to build the latest master of backward-cpp I get the same issue.

Unfortunately I couldn't for my life figure out how to install libiberty on Mac, so created this: https://stackoverflow.com/questions/61863018/how-do-you-install-library-iberty-for-macos

I went with version 1.3.0 instead, but wanted to flag this one, since there might be more ppl experiencing this issue as of the latest update for `backward-cpp`

**Comment by CursedRock17** [comment]
After building on MacOS Ventura (13.2.1) linking liberty was no longer an issue, I don't know if it remains an issue because this discussion has been open for almost 2 years, it also seems like it didn't need an edit in the binutils path, though I disabled SIP.

**Comment by klintan** [comment]
The stackoverflow answer solved it for me. Plus it's def very old now. I'll close it.
